%YAML:1.0
# lidar features
min_plane_dis: 0.2

min_match_sq_dis: 1.0

corner_filter_size: 0.2
surf_filter_size: 0.4
map_filter_size: 0.6

# window sizes
window_size: 7
opt_window_size: 5

init_window_factor: 1

# Extrinsic parameter between IMU and Camera (adapted from VINS-mono)
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.
opt_extrinsic: 1

extrinsic_rotation: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1,  0,  0,
         0,  1,  0,
         0,  0,  1]
 
 #Translation from imu frame to laser frame, laser^T_imu
extrinsic_translation: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [-2.4, 0, 0.7]

# optimization options
run_optimization: 1

update_laser_imu: 1
gravity_fix: 1

plane_projection_factor: 0

imu_factor: 1
point_distance_factor: 1

prior_factor: 0

marginalization_factor: 1

odom_io: 3

pcl_viewer: 0

# IMU noises
acc_n: 0.2
gyr_n: 0.02
acc_w: 0.0002
gyr_w: 2.0e-5
g_norm: 9.80

# lidar deskew
enable_deskew: 1
cutoff_deskew: 0

keep_features: 0

msg_time_delay: 0.05